'use strict';
const TODAY = new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const labels = {dashboard:'Ringkasan',stock:'Inventori',sales:'Penjualan',books:'Pembukuan',cards:'Kartu kredit',tax:'Pajak',settings:'Pengaturan',data:'Data & backup'};
const icons = {dashboard:'layout-dashboard',stock:'package',sales:'shopping-bag',books:'book-open'};
const fees = Object.assign(Object.create(null),{Shopee:0.065,Tokopedia:0.05,WhatsApp:0,Toko:0});
const money = n => 'Rp ' + Math.round(n).toLocaleString('id-ID');
const compact = n => (n/1000000).toLocaleString('id-ID',{maximumFractionDigits:1}) + ' jt';
const date = s => new Date(s+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short'});
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = n => `<i data-lucide="${n}"></i>`;
const el = id => document.getElementById(id);
let inventory, sales, expenses;
let view='dashboard', period='month', query='', filter='all', channel='all', page=1, sort='date', graphMetric='revenue', toastTimer, lastFocus;
const pageSize=6;


const productById = id => inventory.find(p=>p.id===id);
const inPeriod = s => s>=periodStart() && s<=periodEnd();
const periodSales = () => sales.filter(s=>inPeriod(s.date));
const sum = (rows,fn) => rows.reduce((n,r)=>n+fn(r),0);
const revenue = s => s.price*s.qty;
const profit = s => revenue(s)-s.cost*s.qty-s.fee-(s.shipping||0);
function metrics(){const rows=periodSales();return {rows,revenue:sum(rows,revenue),profit:sum(rows,profit),expense:sum(reportExpenses().filter(e=>inPeriod(e.date)),e=>e.amount),pending:sum(rows.filter(s=>s.status==='pending'),s=>revenue(s)-s.fee),units:sum(rows,s=>s.qty),stock:sum(inventory,p=>p.cost*Math.max(0,p.qty)),stockUnits:sum(inventory,p=>Math.max(0,p.qty))};}
function channelHtml(name){const c=channels.find(c=>c.name===name);const color=c?.color||'#768079';return `<span class="channel"><span class="channel-mark" style="color:${color};background:${color}15">${c?.logo?`<img class="channel-logo" src="${c.logo}" alt="">`:esc(name.slice(0,1))}</span>${esc(name)}</span>`;}
function productHtml(p){return `<div class="product"><span class="product-thumb ${p.id==='p5'?'pink':p.brand==='Samsung'?'blue':''}">${icon('smartphone')}</span><div><div class="product-name">${esc(p.name)}</div><div class="product-sub">${esc(p.variant)}</div></div></div>`;}
function statusHtml(status){return `<span class="badge ${status==='pending'?'pending':''}">${status==='pending'?'Belum cair':'Lunas'}</span>`;}
function stockStatus(p){return p.qty<=0?'<span class="badge neutral">Habis</span>':p.qty<=1?'<span class="badge low">Stok menipis</span>':'<span class="badge">Tersedia</span>';}
function heading(){
  const subtitles={dashboard:'Ringkasan penjualan dan hal yang perlu ditindaklanjuti.',data:'',stock:'Setiap unit, nilai stok, dan sumber pembeliannya.',sales:'Transaksi, margin, dan pencairan penjualan.',books:'Laba transaksi, beban operasional, dan laba setelah beban.',cards:'Limit, pemakaian stok, dan pembayaran porsi bisnis.',tax:'Rekap tahunan, estimasi pajak, dan setoran tercatat.',settings:'Channel, supplier, pilihan produk, dan identitas toko.'};
  const primary={stock:['add-stock','Barang masuk'],books:['add-expense','Catat beban'],cards:['edit-card','Tambah kartu'],tax:['tax-pay','Catat setoran']};
  const action=primary[view]||['add-sale','Catat penjualan'];
  let controls=['dashboard','sales','books'].includes(view)?`<label class="period">${icon('calendar-days')}<select id="period" aria-label="Periode laporan">${periodOptions.map(([key,label])=>`<option value="${key}" ${period===key?'selected':''}>${label}</option>`).join('')}</select></label>`:'';
  if(view==='tax')controls=`<label class="period">${icon('calendar-days')}<select id="taxYear" aria-label="Tahun pajak">${reportYears().map(y=>`<option ${taxYear===y?'selected':''}>${y}</option>`).join('')}</select></label>`;
  if(!['settings','data'].includes(view))controls+=`<button class="button export-button" data-action="export" title="Unduh laporan CSV" aria-label="Unduh laporan CSV">${icon('download')}<span class="export-label">Ekspor</span></button><button class="button primary" data-action="${action[0]}">${icon('plus')}${action[1]}</button>`;
  return `<div class="page-heading"><div><span class="eyebrow">${esc(business.name.toUpperCase())}</span><h1>${view==='dashboard'?'Ringkasan bisnis':labels[view]}</h1><p class="subtitle">${subtitles[view]}</p></div><div class="heading-actions">${controls}</div></div>`;
}
function kpi(label,value,foot,ico){return `<div class="kpi"><div class="kpi-label">${label}<span class="metric-icon">${icon(ico)}</span></div><div class="kpi-value"><small>Rp</small>${compact(value)}</div><div class="kpi-foot">${foot}</div></div>`;}
function kpis(){const m=metrics(); const net=m.profit-m.expense;return `<section class="kpis" aria-label="Ringkasan angka">${kpi('Omzet penjualan',m.revenue,`${m.rows.length} transaksi <span class="muted">/ ${m.units} unit terjual</span>`,'shopping-bag')}${kpi('Laba setelah beban',net,`<span class="${net>=0?'positive':'red-text'}">Margin ${m.revenue?(net/m.revenue*100).toFixed(1):'0'}%</span> / termasuk biaya operasional`,'trending-up')}${kpi('Nilai stok saat ini',m.stock,`${m.stockUnits} unit / posisi ${date(TODAY)}`,'package')}${kpi('Dana belum cair',m.pending,`${m.rows.filter(s=>s.status==='pending').length} transaksi dalam periode terpilih`,'wallet')}</section>`;}
function dashboard(){const low=inventory.filter(p=>p.qty>0&&p.qty<=1),old=inventory.filter(p=>p.qty>0&&p.age>30),pending=periodSales().filter(s=>s.status==='pending');return kpis()+`<section class="analysis-grid"><div class="trend"><div class="section-heading"><div><h2>Performa penjualan</h2><p>${periodLabel()}</p></div><div class="segmented" aria-label="Metrik grafik"><button data-metric="revenue" class="${graphMetric==='revenue'?'active':''}">Omzet</button><button data-metric="profit" class="${graphMetric==='profit'?'active':''}">Laba transaksi</button></div></div><div class="legend"><span><b></b>${graphMetric==='revenue'?'Omzet harian':'Laba transaksi harian'}</span><span>Dalam juta rupiah</span></div><div class="chart"><canvas id="chart" role="img" aria-label="Grafik penjualan harian periode terpilih"></canvas><span id="chartTooltip" class="chart-tooltip" hidden></span></div></div><div class="attention"><div class="section-heading"><h2>Perlu perhatian</h2><span class="count-badge">${low.length+old.length+pending.length}</span></div><div class="attention-list"><button class="attention-row" data-go="stock" data-filter="low"><span class="attention-icon">${icon('package-minus')}</span><div><h3>${low.length} produk hampir habis</h3><p>Sisa 1 unit. Cek kebutuhan restok.</p></div>${icon('chevron-right')}</button><button class="attention-row" data-go="stock" data-filter="aging"><span class="attention-icon red">${icon('clock-3')}</span><div><h3>${old.length} produk tersimpan &gt;30 hari</h3><p>${money(sum(old,p=>Math.max(0,p.qty)*p.cost))} masih di stok.</p></div>${icon('chevron-right')}</button><button class="attention-row" data-go="sales" data-filter="pending"><span class="attention-icon blue">${icon('wallet')}</span><div><h3>${pending.length} pencairan perlu dicek</h3><p>Penerimaan penjualan belum dikonfirmasi.</p></div>${icon('chevron-right')}</button></div></div></section><section><div class="section-heading"><div><h2>Transaksi terbaru</h2><p>Aktivitas penjualan dalam periode terpilih</p></div><button class="text-link" data-go="sales">Semua transaksi ${icon('arrow-up-right')}</button></div>${salesTable(periodSales().slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5),true)}</section>`;}
function salesTable(rows,brief=false){return `<div class="table-scroll"><table class="sales-table"><thead><tr><th>Tanggal</th><th>Produk / transaksi</th><th>Channel</th><th class="numeric">Total penjualan</th><th class="numeric">Laba transaksi</th><th>Status dana</th><th><span aria-label="Detail"></span></th></tr></thead><tbody>${rows.length?rows.map(s=>`<tr data-detail="sale" data-id="${s.id}"><td class="muted sale-date">${date(s.date)}<small>${s.date.slice(0,4)}</small></td><td>${productHtml(productById(s.productId))}<div class="product-sub" style="margin-left:46px">${s.id} / ${s.qty} unit</div></td><td>${channelHtml(s.channel)}</td><td class="numeric">${money(revenue(s))}</td><td class="numeric green">${money(profit(s))}</td><td>${statusHtml(s.status)}</td><td><div class="sale-actions"><button class="icon-button" data-action="edit-sale" data-id="${s.id}" aria-label="Edit ${s.id}" title="Edit penjualan">${icon('pencil')}</button><button class="icon-button" data-detail="sale" data-id="${s.id}" aria-label="Detail ${s.id}" title="Detail transaksi">${icon('arrow-up-right')}</button></div></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Tidak ada transaksi yang cocok.</td></tr>'}</tbody></table></div>${brief?`<div class="table-foot"><span>${rows.length} transaksi terbaru</span><span>Semua nominal dalam rupiah</span></div>`:''}`;}
function searchBox(placeholder){return `<label class="search-box">${icon('search')}<input id="search" type="search" aria-label="${placeholder}" placeholder="${placeholder}" value="${esc(query)}"></label>`;}
function tabs(items){return `<div class="view-tabs" role="group" aria-label="Filter status">${items.map(([value,label,count])=>`<button data-filter-tab="${value}" class="${filter===value?'active':''}" aria-pressed="${filter===value}">${label}<span>${count}</span></button>`).join('')}</div>`;}
function filteredInventory(){return inventory.filter(p=>(filter==='all'||filter==='available'&&p.qty>0||filter==='low'&&p.qty>0&&p.qty<=1||filter==='aging'&&p.qty>0&&p.age>30||filter==='empty'&&p.qty<=0)&&(channel==='all'||p.brand===channel)&&(supplierFilter==='all'||p.supplierId===supplierFilter)&&`${p.name} ${p.variant} ${esc(p.sku)} ${p.supplier}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='qty'?a.qty-b.qty:sort==='cost'?b.cost-a.cost:a.name.localeCompare(b.name));}
function filteredSales(){return periodSales().filter(s=>(filter==='all'||s.status===filter)&&(channel==='all'||s.channel===channel)&&`${productById(s.productId).name} ${s.id} ${s.buyer}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='profit'?profit(b)-profit(a):b.date.localeCompare(a.date));}
function pager(total){const pages=Math.max(1,Math.ceil(total/pageSize));page=Math.min(page,pages);return `<div class="table-foot"><span class="page-description">Menampilkan ${total?(page-1)*pageSize+1:0}-${Math.min(page*pageSize,total)} dari ${total} ${view==='stock'?'produk':'transaksi'}</span><div class="pagination"><button class="icon-button" data-page="${page-1}" ${page<=1?'disabled':''} title="Halaman sebelumnya" aria-label="Halaman sebelumnya">${icon('chevron-left')}</button><span class="page-number">${page}</span><span>dari ${pages}</span><button class="icon-button" data-page="${page+1}" ${page>=pages?'disabled':''} title="Halaman berikutnya" aria-label="Halaman berikutnya">${icon('chevron-right')}</button></div></div>`;}
function stockTable(rows){return `<div class="table-scroll"><table><thead><tr><th>Produk</th><th>SKU</th><th class="numeric">HPP / unit</th><th class="numeric"><button class="sort-button" data-sort="qty">Sisa ${icon('arrow-up-down')}</button></th><th>Usia stok</th><th>Status</th><th></th></tr></thead><tbody>${rows.length?rows.map(p=>`<tr data-detail="stock" data-id="${p.id}"><td>${productHtml(p)}</td><td class="muted">${esc(p.sku)}</td><td class="numeric">${money(p.cost)}</td><td class="numeric"><strong>${p.qty}</strong><span class="muted"> unit</span></td><td>${p.age} hari<div class="stock-age">${p.age>30?'Perlu evaluasi':'Perputaran normal'}</div></td><td>${stockStatus(p)}</td><td><button class="icon-button" data-detail="stock" data-id="${p.id}" title="Detail stok" aria-label="Detail ${esc(p.name)}">${icon('arrow-up-right')}</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Tidak ada produk yang cocok.</td></tr>'}</tbody></table></div>`;}
function listView(){const isStock=view==='stock';const rows=isStock?filteredInventory():filteredSales();const t= isStock?[['all','Semua produk',inventory.length],['low','Stok menipis',inventory.filter(p=>p.qty===1).length],['aging','Stok lama',inventory.filter(p=>p.qty&&p.age>30).length],['empty','Habis',inventory.filter(p=>!p.qty).length]]:[['all','Semua transaksi',periodSales().length],['unknown','Belum diketahui',periodSales().filter(s=>s.status==='unknown').length],['pending','Belum cair',periodSales().filter(s=>s.status==='pending').length],['paid','Lunas',periodSales().filter(s=>s.status==='paid').length]];page=Math.min(page,Math.max(1,Math.ceil(rows.length/pageSize)));const options=isStock?[...new Set(inventory.map(p=>p.brand))]:[...new Set([...channels.map(c=>c.name),...sales.map(s=>s.channel)])];return `${isStock?`<p class="stock-summary"><strong>${sum(inventory,p=>Math.max(0,p.qty))} unit</strong> tersedia / nilai persediaan <strong>${money(sum(inventory,p=>Math.max(0,p.qty)*p.cost))}</strong></p>`:kpis()}${tabs(t)}<div class="table-toolbar">${searchBox(isStock?'Cari produk, SKU, atau supplier...':'Cari produk, transaksi, atau pembeli...')}<div class="filters"><select id="channel" aria-label="${isStock?'Merek':'Channel'}"><option value="all">${isStock?'Semua merek':'Semua channel'}</option>${options.map(c=>`<option ${c===channel?'selected':''}>${esc(c)}</option>`).join('')}</select>${isStock?`<select id="supplierFilter" aria-label="Supplier"><option value="all">Semua supplier</option>${suppliers.map(s=>`<option value="${s.id}" ${supplierFilter===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`:''}<select id="sort" aria-label="Urutan"><option value="date">${isStock?'Nama produk':'Terbaru'}</option><option value="${isStock?'qty':'profit'}" ${sort===(isStock?'qty':'profit')?'selected':''}>${isStock?'Stok terendah':'Laba tertinggi'}</option>${isStock?`<option value="cost" ${sort==='cost'?'selected':''}>HPP tertinggi</option>`:''}</select></div></div><div id="listResults">${isStock?stockTable(rows.slice((page-1)*pageSize,page*pageSize)):salesTable(rows.slice((page-1)*pageSize,page*pageSize))}${pager(rows.length)}</div>`;}
function bookLine(label,value,total=false,format=money){return `<div class="book-line ${total?'total':''}"><span>${esc(label)}</span><strong>${format(value)}</strong></div>`;}
function booksView(){const m=metrics();const rows=m.rows,selectedExpenses=reportExpenses().filter(e=>inPeriod(e.date)).sort((a,b)=>b.date.localeCompare(a.date));return kpis()+`<div class="book-grid"><section><div class="section-heading"><h2>Laporan laba rugi</h2><span class="badge neutral">${periodLabel()}</span></div>${bookLine('Omzet penjualan',m.revenue)}${bookLine('Harga pokok penjualan',-sum(rows,s=>s.qty*s.cost))}${bookLine('Biaya marketplace',-sum(rows,s=>s.fee))}${bookLine('Ongkir penjualan',-sum(rows,s=>s.shipping||0))}${bookLine('Laba transaksi',m.profit)}${bookLine('Beban operasional',-m.expense)}${bookLine('Laba setelah beban',m.profit-m.expense,true)}<p class="cash-note">Laba sebelum pajak. Dana belum cair tetap tercatat sebagai piutang.</p></section><section><div class="section-heading"><h2>Arus penerimaan penjualan</h2>${icon('wallet')}</div>${bookLine('Dana diterima',sum(rows.filter(s=>s.status==='paid'),s=>revenue(s)-s.fee))}${bookLine('Dana belum cair',m.pending)}<p class="cash-note">Penerimaan setelah biaya marketplace, sebelum pembayaran stok dan beban.</p><div class="section-heading" style="margin-top:27px"><h2>Beban operasional</h2><button class="text-link" data-action="add-expense">${icon('plus')}Tambah</button></div>${selectedExpenses.length?selectedExpenses.map(e=>`<div class="expense-row"><div><strong>${esc(e.name)}</strong><p>${date(e.date)} / ${esc(e.category)}</p></div><span>${money(e.amount)}</span></div>`).join(''):'<p class="muted">Belum ada beban pada periode ini.</p>'}</section></div>`;}
function refreshIcons(){if(window.lucide)lucide.createIcons();}
function render(){document.body.dataset.view=view;el('main').innerHTML=heading()+(view==='dashboard'?dashboard():view==='books'?booksView()+creditBooks():moduleViews[view]?moduleViews[view]():listView());el('crumb').textContent=labels[view];el('stockCount').textContent=sum(inventory,p=>Math.max(0,p.qty));document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===view));document.querySelector('.profile strong').textContent=business.owner;document.querySelector('.avatar').textContent=business.owner.slice(0,1).toUpperCase();document.title=business.name+' | Workspace';updateStorageBadge();refreshIcons();if(view==='dashboard')requestAnimationFrame(drawChart);}
function go(next,f='all'){view=labels[next]?next:'dashboard';filter=f;query='';channel='all';supplierFilter='all';page=1;sort='date';history.replaceState(null,'','#'+view);render();closeNav();window.scrollTo(0,0);}
function drawChart(){const canvas=el('chart');if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,left=30,top=8,bottom=27,right=9,start=period==='week'?21:1,count=28-start;const values=Array.from({length:count},(_,i)=>sum(periodSales().filter(s=>Number(s.date.slice(-2))===start+i),graphMetric==='revenue'?revenue:profit)/1e6);const max=Math.max(1,Math.ceil(Math.max(...values)/5)*5);const X=i=>left+i/(count-1)*(w-left-right);const Y=v=>h-bottom-v/max*(h-top-bottom);ctx.font='10px Segoe UI';ctx.textBaseline='middle';ctx.fillStyle='#96a198';ctx.lineWidth=1;
  for(let i=0;i<=3;i++){const value=max*i/3,y=Y(value);ctx.fillText(Math.round(value),0,y);ctx.beginPath();ctx.setLineDash([3,4]);ctx.strokeStyle='#e5ece6';ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke();}
  ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(X(0),Y(0));values.forEach((v,i)=>ctx.lineTo(X(i),Y(v)));ctx.lineTo(X(count-1),Y(0));ctx.closePath();ctx.fillStyle='#edf5ee';ctx.fill();ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(X(i),Y(v)):ctx.moveTo(X(i),Y(v)));ctx.strokeStyle='#267c5e';ctx.lineWidth=2;ctx.lineJoin='round';ctx.stroke();ctx.fillStyle='#98a198';ctx.textAlign='center';for(let i=0;i<count;i++){if(i===0||i===count-1||(i%(period==='week'?2:(w<450?7:5))===0 && X(count-1)-X(i)>52))ctx.fillText(String(start+i).padStart(2,'0')+' Sep',Math.max(39,Math.min(w-25,X(i))),h-7);}canvas.onmousemove=e=>{const index=Math.max(0,Math.min(count-1,Math.round((e.offsetX-left)/(w-left-right)*(count-1))));const tip=el('chartTooltip');tip.hidden=false;tip.textContent=`${start+index} Sep / ${money(values[index]*1e6)}`;};canvas.onmouseleave=()=>el('chartTooltip').hidden=true;
}
function toast(text){clearTimeout(toastTimer);el('toast').textContent=text;el('toast').classList.add('show');toastTimer=setTimeout(()=>el('toast').classList.remove('show'),3200);}
function openDrawer(title,body,eyebrow='WORKSPACE'){lastFocus=document.activeElement;el('drawerTitle').textContent=title;el('drawerEyebrow').textContent=eyebrow;el('drawerBody').innerHTML=body;el('drawer').showModal();document.body.style.overflow='hidden';refreshIcons();}
function closeDrawer(){el('drawer').close();document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus();}
function field(label,name,type,value='',extra=''){return `<label class="form-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function formFooter(label){return `<p id="formError" class="form-error" role="alert"></p><div class="form-footer"><button type="button" class="button" data-action="cancel">Batal</button><button class="button primary" type="submit">${icon('check')}${label}</button></div>`;}
function saleForm(productId){
  const available=inventory.filter(p=>p.qty>0);if(!available.length){toast('Stok habis. Tambahkan barang masuk terlebih dahulu.');return;}
  const p=productById(productId)||available[0];
  openDrawer('Catat penjualan',`<form id="saleForm"><label class="form-field"><span>Produk</span><select name="productId" id="saleProduct">${available.map(p=>`<option value="${p.id}" ${p.id===productId?'selected':''}>${esc(p.name)} / ${esc(p.variant)}</option>`).join('')}</select><p class="form-hint" id="available">Sisa ${p.qty} unit / HPP ${money(p.cost)}</p></label><div class="field-pair">${field('Tanggal','date','date',TODAY,`required max="${TODAY}" min="2000-01-01"`)}${field('Jumlah unit','qty','number',1,`required min="1" max="${p.qty}" step="1"`)}</div>${field('Harga jual per unit (Rp)','price','number',p.price,'required min="1" step="1"')}<div class="field-pair"><label class="form-field"><span>Channel</span><select name="channel">${channels.filter(c=>c.active).map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}</select></label><label class="form-field"><span>Status dana</span><select name="status"><option value="pending">Belum cair</option><option value="paid">Lunas</option></select></label></div><div class="field-pair">${field('Biaya admin manual (Rp)','adminOverride','number','','min="0" step="1" placeholder="Otomatis dari channel"')}${field('Ongkir ditanggung (Rp)','shipping','number',0,'required min="0" step="1"')}</div>${field('Nama pembeli','buyer','text','','required maxlength="80"')}<div class="estimate"><span>Biaya marketplace</span><strong id="estimatedFee"></strong></div><div class="estimate"><span>Estimasi laba transaksi</span><strong class="green" id="estimatedProfit"></strong></div>${formFooter('Simpan penjualan')}</form>`,'PENJUALAN BARU');updateEstimate();
}
function updateEstimate(){const f=el('saleForm');if(!f)return;const p=productById(f.elements.productId.value),qty=Number(f.elements.qty.value),price=Number(f.elements.price.value);const manual=f.elements.adminOverride.value,fee=manual!==''?Number(manual):Math.round(price*qty*fees[f.elements.channel.value]);el('estimatedFee').textContent=money(fee);el('estimatedProfit').textContent=money(price*qty-p.cost*qty-fee-Number(f.elements.shipping.value||0));}
function stockForm(){openDrawer('Barang masuk',`<form id="stockForm">${field('Nama produk','name','text','','required maxlength="80"')}${field('Varian / kapasitas / warna','variant','text','','required maxlength="80"')}<div class="field-pair">${selectField('Merek','brand',['Apple','Samsung','Google','Xiaomi','Lainnya'].map(b=>`<option>${b}</option>`).join(''))}${field('Jumlah unit','qty','number',1,'required min="1" max="999" step="1"')}</div><div class="field-pair">${field('HPP per unit (Rp)','cost','number','','required min="1" step="1"')}${field('Harga jual per unit (Rp)','price','number','','required min="1" step="1"')}</div>${selectField('Supplier','supplierId',activeOptions(suppliers))}<div class="field-pair">${selectField('Kategori','category',business.categories.map(v=>`<option>${esc(v)}</option>`).join(''))}${selectField('Kondisi','condition',business.conditions.map(v=>`<option>${esc(v)}</option>`).join(''))}</div>${selectField('Garansi','warranty',business.warranties.map(v=>`<option>${esc(v)}</option>`).join(''))}${selectField('Sumber pembayaran','payMethod','<option value="cash">Tunai / transfer</option>'+cards.filter(c=>c.active).map(c=>`<option value="${c.id}">${esc(cardName(c.id))} / sisa ${money(availableCardLimit(c))}</option>`).join(''))}${stockInstallmentFields()}${formFooter('Simpan barang')}</form>`,'PERSEDIAAN BARU');updateInstallmentFields(el('stockForm'));}
function expenseForm(){openDrawer('Catat beban',`<form id="expenseForm">${field('Keterangan','name','text','','required maxlength="100"')}<div class="field-pair">${field('Tanggal','date','date',TODAY,`required max="${TODAY}" min="2000-01-01"`)}<label class="form-field"><span>Kategori</span><select name="category"><option>Operasional</option><option>Pemasaran</option><option>Sewa</option><option>Utilitas</option></select></label></div>${field('Jumlah (Rp)','amount','number','','required min="1" step="1"')}${formFooter('Simpan beban')}</form>`,'BEBAN OPERASIONAL');}
function detail(kind,id){if(kind==='stock'){const p=productById(id);openDrawer(p.name,`<div class="detail-hero"><span class="product-thumb">${icon('smartphone')}</span><div><h3>${esc(p.variant)}</h3><p>${esc(p.sku)} / ${esc(p.condition)}</p></div></div><div class="detail-lines">${bookLine('HPP per unit',p.cost)}${bookLine('Harga jual',p.price)}<div class="book-line"><span>Sisa stok</span><strong>${p.qty} unit</strong></div><div class="book-line"><span>Usia stok</span><strong>${p.age} hari</strong></div><div class="book-line"><span>Supplier</span><strong>${esc(supplierName(p))}</strong></div><div class="book-line"><span>Garansi</span><strong>${esc(p.warranty||'-')}</strong></div><div class="book-line"><span>Sumber pembayaran</span><strong>${esc(cardName(p.payMethod))}</strong></div><div class="book-line"><span>Status</span>${stockStatus(p)}</div></div><div class="form-footer"><button class="button primary" data-action="sell-product" data-id="${id}" ${p.qty>0?'':'disabled'}>${icon('plus')}Catat penjualan</button></div>`,'DETAIL INVENTORI');}else{const s=sales.find(s=>s.id===id),p=productById(s.productId);openDrawer(s.id,`<div class="detail-hero"><span class="product-thumb">${icon('smartphone')}</span><div><h3>${esc(p.name)}</h3><p>${esc(p.variant)} / ${s.qty} unit</p></div></div><div class="detail-lines"><div class="book-line"><span>Tanggal</span><strong>${date(s.date)} ${s.date.slice(0,4)}</strong></div><div class="book-line"><span>Pembeli</span><strong>${esc(s.buyer)}</strong></div><div class="book-line"><span>Channel</span>${channelHtml(s.channel)}</div>${bookLine('Total penjualan',revenue(s))}${bookLine('Harga pokok',s.cost*s.qty)}${bookLine('Biaya marketplace',s.fee)}${bookLine('Ongkir ditanggung',s.shipping||0)}${bookLine('Laba transaksi',profit(s),true)}<div class="book-line"><span>Status dana</span>${statusHtml(s.status)}</div></div>${s.status!=='paid'?`<div class="form-footer"><button class="button primary" data-action="settle" data-id="${id}">${icon('check')}Tandai sudah cair</button></div>`:''}`,'DETAIL TRANSAKSI');}}
function downloadCsv(){if(moduleExport())return;let rows,name;if(view==='stock'){name='inventori';rows=[['SKU','Produk','Varian','HPP','Sisa unit','Usia stok'],...filteredInventory().map(p=>[p.sku,p.name,p.variant,p.cost,p.qty,p.age])];}else if(view==='books'){const m=metrics();name='pembukuan';rows=[['Pos','Jumlah'],['Omzet',m.revenue],['Laba transaksi',m.profit],['Beban operasional',m.expense],['Laba setelah beban',m.profit-m.expense],['Dana belum cair',m.pending]];}else{name='penjualan';rows=[['Transaksi','Tanggal','Produk','Channel','Jumlah','Omzet','Laba transaksi','Status'],...(view==='sales'?filteredSales():periodSales()).map(s=>[s.id,s.date,productById(s.productId).name,s.channel,s.qty,revenue(s),profit(s),s.status])];}const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`cornetto-${name}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Laporan data berhasil diunduh.');}
function closeNav(){el('sidebar').classList.remove('open');el('navScrim').hidden=true;}
document.addEventListener('click',e=>{
  const a=e.target.closest('[data-action],[data-nav],[data-go],[data-filter-tab],[data-page],[data-detail],[data-metric],[data-sort]');if(!a)return;
  if(a.dataset.nav){e.preventDefault();go(a.dataset.nav);return;}
  if(a.dataset.go){go(a.dataset.go,a.dataset.filter||'all');return;}
  if(a.dataset.filterTab){filter=a.dataset.filterTab;page=1;render();return;}
  if(a.dataset.page){page=Number(a.dataset.page);render();return;}
  if(a.dataset.metric){graphMetric=a.dataset.metric;render();return;}
  if(a.dataset.sort){sort=a.dataset.sort;render();return;}
  if(a.dataset.detail){detail(a.dataset.detail,a.dataset.id);return;}
  if(handleModuleClick(a))return;
  switch(a.dataset.action){case 'edit-sale':editSaleForm(a.dataset.id);break;case 'add-sale':saleForm();break;case 'add-stock':stockForm();break;case 'add-expense':expenseForm();break;case 'cancel':closeDrawer();break;case 'export':downloadCsv();break;case 'sell-product':closeDrawer();saleForm(a.dataset.id);break;case 'settle':sales.find(s=>s.id===a.dataset.id).status='paid';saveDemo();closeDrawer();render();toast('Dana ditandai sudah cair pada data.');break;}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;page=1;const rows=view==='stock'?filteredInventory():filteredSales();el('listResults').innerHTML=(view==='stock'?stockTable(rows.slice(0,pageSize)):salesTable(rows.slice(0,pageSize)))+pager(rows.length);refreshIcons();}if(e.target.closest('#saleForm'))updateEstimate();});
document.addEventListener('change',e=>{if(handleModuleChange(e))return;if(e.target.id==='period'){period=e.target.value;page=1;render();}if(e.target.id==='channel'){channel=e.target.value;page=1;render();}if(e.target.id==='sort'){sort=e.target.value;page=1;render();}if(e.target.id==='saleProduct'){const p=productById(e.target.value),f=el('saleForm');f.elements.price.value=p.price;f.elements.qty.max=p.qty;f.elements.qty.value=1;el('available').textContent=`Sisa ${p.qty} unit / HPP ${money(p.cost)}`;updateEstimate();}});
document.addEventListener('submit',e=>{
  if(handleModuleSubmit(e))return;
  const f=e.target;if(!['saleForm','stockForm','expenseForm'].includes(f.id))return;e.preventDefault();const data=f.id==='stockForm'?installmentFormData(f):Object.fromEntries(new FormData(f));
  if(f.id==='saleForm'){
    const p=productById(data.productId),qty=Number(data.qty),price=Number(data.price),shipping=Number(data.shipping||0),fee=data.adminOverride!==''?Number(data.adminOverride):Math.round(qty*price*fees[data.channel]);
    const ch=channels.find(c=>c.active&&c.name===data.channel);
    if(!p||!ch||!Number.isInteger(qty)||qty<1||qty>p.qty||!validAmount(price)||price<=0||!validAmount(shipping)||!validAmount(fee)){formError('Periksa harga, biaya, dan jumlah. Penjualan tidak boleh melebihi stok.');return;}
    p.qty-=qty;sales.unshift({id:nextId('CS'),productId:p.id,date:data.date,qty,price,cost:p.cost,fee,shipping,channel:data.channel,channelId:ch.id,buyer:data.buyer.trim(),status:data.status});
  }else if(f.id==='stockForm'){if(!commitStock(data))return;}
  else{expenses.unshift({name:data.name.trim(),date:data.date,category:data.category,amount:Number(data.amount)});}
  saveDemo();closeDrawer();render();toast('Perubahan dicatat.');
});
el('menu').onclick=()=>{el('sidebar').classList.add('open');el('navScrim').hidden=false;};el('navScrim').onclick=closeNav;
el('closeDrawer').onclick=closeDrawer;el('drawer').addEventListener('cancel',()=>{document.body.style.overflow='';});el('drawer').addEventListener('click',e=>{if(e.target===el('drawer')){const r=el('drawer').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right)closeDrawer();}});

window.addEventListener('resize',drawChart);window.addEventListener('hashchange',()=>go(location.hash.slice(1)));

